version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sinatra_app
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: sinatra_app
#    ports:
#      - "4567:4567"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db:5432/sinatra_app

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin

#volumes:
#  postgres_data:
#  pgadmin_data:
